### PR TITLE
[amvideocap] - add support for aml video capture device (needed for bobl...

### PR DESCRIPTION
**Pull request by Memphiz**
...ight support)

This besically enables /dev/amvideocap for capturing video frames during playback. I guess this can work on other aml platforms aswell - but i was not sure where else you already switched to device tree files - so wetek.play for now only.

this is the base for https://github.com/OpenELEC/OpenELEC.tv/pull/3782

### CODE REVIEW

**Comment by Memphiz** [comment]
Updated to use the same device name as in meson8m2_n01_2G.dtd and meson8_k200a_2G_4k2k.dtd

**Comment by codesnake** [comment]
I think you can now create the same PR to the main OE repository :)

**Comment by Memphiz** [comment]
nice - will do :)

**Comment by Memphiz** [comment]
@codesnake so basically all kernel patches are done as patches against OE via the patches folder? Or is there some aml kernel repo somewhere where those should go to? (i don't mean dts patches but real c-driver patches)

**Comment by codesnake** [comment]
Amlogic kernel repository is here: https://github.com/codesnake/linux-amlogic

**Comment by Memphiz** [comment]
@codesnake you want me to do PRs against the kernel tree in addition? (would be no problem)

**Comment by codesnake** [comment]
Would be good.

**Pull request closed without merging**
